/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author carme
 */
public class GUI extends javax.swing.JFrame {
    private String correo;
    private String password;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_gui_ingresar = new javax.swing.JButton();
        btn_gui_registrar = new javax.swing.JButton();
        txt_gui_ingresarCorreo = new javax.swing.JTextField();
        pass_gui_ingresarPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Correo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, -1));

        btn_gui_ingresar.setBackground(new java.awt.Color(0, 153, 153));
        btn_gui_ingresar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_gui_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_gui_ingresar.setText("Ingresar");
        btn_gui_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gui_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gui_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 100, 30));

        btn_gui_registrar.setBackground(new java.awt.Color(0, 153, 153));
        btn_gui_registrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_gui_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_gui_registrar.setText("Registrar");
        getContentPane().add(btn_gui_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 30));
        getContentPane().add(txt_gui_ingresarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 115, 170, -1));
        getContentPane().add(pass_gui_ingresarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 153, 170, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mint Eye Ticket Service");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\carme\\Documents\\TEC\\I SEMESTRE 2018\\DISEÑO DE SOFTWARE\\Proyecto1\\TicketService\\images\\bk.JPG")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 440, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gui_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gui_ingresarActionPerformed
        if (txt_gui_ingresarCorreo.getText().equals("") || String.valueOf(pass_gui_ingresarPassword.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(null,"Dejo algun espacio vacio");

       }
       else{           
           DTOGUI dtologin = new DTOGUI(txt_gui_ingresarCorreo.getText(), String.valueOf(pass_gui_ingresarPassword.getPassword()));   
           if(dtologin.logIn() == true){
               JOptionPane.showMessageDialog(null,"Que carga que es monse");
           }
           else{
               JOptionPane.showMessageDialog(null,"Los datos introducidos son incorrectos");
           }
        }
    }//GEN-LAST:event_btn_gui_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gui_ingresar;
    private javax.swing.JButton btn_gui_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pass_gui_ingresarPassword;
    private javax.swing.JTextField txt_gui_ingresarCorreo;
    // End of variables declaration//GEN-END:variables
}
